name: orvokki
version: 0.0.1
synopsis: APL like calculator
description: See README at <https://github.com/japiirainen/orvokki#readme>
maintainer: Joona Piirainen <joona.piirainen@gmail.com>
github: japiirainen/orvokki
category: Development
extra-source-files:
  - CHANGELOG.md

ghc-options: -Wall

dependencies:
    - base
    - Earley
    - ansi-terminal
    - containers
    - filepath
    - generic-lens
    - haskeline
    - http-client
    - http-client-tls
    - http-types
    - insert-ordered-containers
    - lens
    - megaparsec
    - modern-uri
    - mtl
    - optparse-applicative
    - parser-combinators
    - prettyprinter
    - prettyprinter-ansi-terminal
    - repline
    - safe-exceptions
    - scientific
    - string-interpolate
    - template-haskell
    - terminal-size
    - text
    - unordered-containers

library:
  source-dirs: src
  exposed-modules:
    - Orvokki
    - Orvokki.Location
    - Orvokki.Lexer
    - Orvokki.Parser
    - Orvokki.REPL
    - Orvokki.Pretty
    - Orvokki.Syntax
    - Orvokki.Input


executable:
  main: Main.hs
  source-dirs: app
  dependencies:
    - orvokki

tests:
  tasty:
    main: Main.hs
    source-dirs: tasty

    dependencies:
      - base
      - orvokki
      - parsec
      - megaparsec
      - mtl
      - template-haskell
      - ansi-wl-pprint
      - tasty
      - tasty-hunit
      - prettyprinter
      - transformers
      - haskeline
      - containers
      - pretty
      - text
      - repline
